/* SIXTH - NINTH PROGRAMMING EXERCISES*/
/* SUBMITTED BY: ANDREI CAPILI (BSCPE 1-1 - PUP BC)*/
/* LOTTERY NUMBER GENERATOR*/

#include <iostream>
#include <random>
using namespace std;

string greetUser (){
        string userName;
        cout<<"Hi! What's your name?:";
        cin>>userName;
        cout<<"Good day! " + userName + ", This program is designed to generate random numbers."<<endl;
        return userName;
    };

void lotteryNumberGenerator(){
    int lotteryNumbers[7] = {};
    random_device randomizer; 
    
    uniform_int_distribution<int> lotteryNumber(0, 9); 
    // Determines the minimum and maximum randomizer values that shall be assigned to the int variable lotteryNumber.

    for(int loop = 0; loop < (sizeof(lotteryNumbers)/sizeof(int)); loop++){ 
        // C++ retrieves the sizeof() value in bytes, which is 4x the size of int. 
        // To get the int value, divide the size of operator value by sizeof(int), which is 4.
        
        lotteryNumbers[loop] = lotteryNumber(randomizer); 
        // Based on the loop number, the array will include a pseudorandom value generated by the random device randomizer function.
        cout << lotteryNumbers[loop] << " ";
    }
}

int main(){
    string userName;
    userName = greetUser();
    cout << "Generated Lottery Numbers: ";
    lotteryNumberGenerator();
}