
import java.util.Random;
import java.util.Scanner;

public class capililotterynum {

	/* SIXTH - NINTH PROGRAMMING EXERCISES*/
	/* SUBMITTED BY: ANDREI CAPILI (BSCPE 1-1 - PUP BC)*/ 
	/* LOTTERY NUMBER GENERATOR*/
	

	 public static void NameAsk(){
	        Scanner input = new Scanner(System.in);
	        System.out.print("Hi! What's your name?: ");
	        String userName = input.nextLine();
	        introText(userName);
	        

	        input.close();
	    }
	    public static void introText (String userName) {
	        System.out.println("Good day! " + userName + ", This program is designed to generate random numbers.");
		
	    }
	    
	    public static void RandomLotteryNumberyGenerator(){

	    	
	        Random randomizer = new Random();
	        int[] lotteryNumbers = new int[7];
	        
	        for(int loop = 0; loop < lotteryNumbers.length; loop++){
	            lotteryNumbers[loop] = randomizer.nextInt(10); 
	            
	            // The array lotteryNumbers according to loop number will generate a 
	            // pseudorandom value generated by the Random randomizer function
	            // from 0 to 9 (10 Elements)
	            
	            System.out.print(lotteryNumbers[loop] + " ");
	        }
	    }
	    
	    public static void NumberGenerator() {
	    	System.out.print("Generated Lottery Numbers: ");
	    	
	    }
	    	
	    public static void main(String[] args) {
	        
	        NameAsk();
	        introText();
	        NumberGenerator();
	        RandomLotteryNumberyGenerator();
	        
	    }
		private static void introText() {
			// TODO Auto-generated method stub
			
		}
	}	


